// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CZERTAINLY/CBOM-lens/internal/walk/registry (interfaces: RegistryKey)
//
// Generated by this command:
//
//	mockgen -destination mock/mock_registry.go -package mock . RegistryKey
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	registry "github.com/CZERTAINLY/CBOM-lens/internal/walk/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryKey is a mock of RegistryKey interface.
type MockRegistryKey struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryKeyMockRecorder
	isgomock struct{}
}

// MockRegistryKeyMockRecorder is the mock recorder for MockRegistryKey.
type MockRegistryKeyMockRecorder struct {
	mock *MockRegistryKey
}

// NewMockRegistryKey creates a new mock instance.
func NewMockRegistryKey(ctrl *gomock.Controller) *MockRegistryKey {
	mock := &MockRegistryKey{ctrl: ctrl}
	mock.recorder = &MockRegistryKeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryKey) EXPECT() *MockRegistryKeyMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRegistryKey) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRegistryKeyMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRegistryKey)(nil).Close))
}

// OpenSubKey mocks base method.
func (m *MockRegistryKey) OpenSubKey(path string) (registry.RegistryKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenSubKey", path)
	ret0, _ := ret[0].(registry.RegistryKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenSubKey indicates an expected call of OpenSubKey.
func (mr *MockRegistryKeyMockRecorder) OpenSubKey(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenSubKey", reflect.TypeOf((*MockRegistryKey)(nil).OpenSubKey), path)
}

// ReadBinaryValue mocks base method.
func (m *MockRegistryKey) ReadBinaryValue(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBinaryValue", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBinaryValue indicates an expected call of ReadBinaryValue.
func (mr *MockRegistryKeyMockRecorder) ReadBinaryValue(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBinaryValue", reflect.TypeOf((*MockRegistryKey)(nil).ReadBinaryValue), name)
}

// ReadStringValue mocks base method.
func (m *MockRegistryKey) ReadStringValue(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStringValue", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStringValue indicates an expected call of ReadStringValue.
func (mr *MockRegistryKeyMockRecorder) ReadStringValue(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStringValue", reflect.TypeOf((*MockRegistryKey)(nil).ReadStringValue), name)
}

// ReadStringsValue mocks base method.
func (m *MockRegistryKey) ReadStringsValue(name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStringsValue", name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStringsValue indicates an expected call of ReadStringsValue.
func (mr *MockRegistryKeyMockRecorder) ReadStringsValue(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStringsValue", reflect.TypeOf((*MockRegistryKey)(nil).ReadStringsValue), name)
}

// ReadSubKeyNames mocks base method.
func (m *MockRegistryKey) ReadSubKeyNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSubKeyNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSubKeyNames indicates an expected call of ReadSubKeyNames.
func (mr *MockRegistryKeyMockRecorder) ReadSubKeyNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSubKeyNames", reflect.TypeOf((*MockRegistryKey)(nil).ReadSubKeyNames))
}

// ReadValueNames mocks base method.
func (m *MockRegistryKey) ReadValueNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadValueNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadValueNames indicates an expected call of ReadValueNames.
func (mr *MockRegistryKeyMockRecorder) ReadValueNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadValueNames", reflect.TypeOf((*MockRegistryKey)(nil).ReadValueNames))
}

// ReadValueType mocks base method.
func (m *MockRegistryKey) ReadValueType(name string) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadValueType", name)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadValueType indicates an expected call of ReadValueType.
func (mr *MockRegistryKeyMockRecorder) ReadValueType(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadValueType", reflect.TypeOf((*MockRegistryKey)(nil).ReadValueType), name)
}
