name: Test Docker image

on:
  pull_request:
    paths-ignore:
      - 'deploy/charts/**'
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}-docker-test
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write

jobs:
  test:
    uses: OmniTrustILM/.github/.github/workflows/containers-test.yml@0638f1be1040e31c4b147a0c77678d313cd46be4 # main
    with:
      image: ilm/cbom-lens
      cache-scope: cbom-lens
      build-args: |
        VERSION=${{ github.ref_name }}
